name: fetch_branch_path
description: Fetch a path from a given branch and optionally remove the existing path first.

inputs:
  branch:
    description: "Branch we want"
    required: true
  path:
    description: "Path of the directory or file we want"
    required: true
  remove:
    description: "Whether to remove the path before fetching (true/false)"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:


    - name: Remove path if required
      if: ${{ inputs.remove == 'true' }}
      shell: bash
      run: |
        echo "Removing path: ${{ inputs.path }}"
        rm -rf -- "${{ inputs.path }}"

    - name: Restore path from branch
      shell: bash
      run: |
        git restore --source "origin/${{ inputs.branch }}" --staged --worktree -- "${{ inputs.path }}"