name: fetch_branch_path
on:
  workflow_call:
    inputs:
      branch:
        description: 'branch we want'
        required: true
        type: string
      path:
        description: 'path of the directory of file we want'
        required: true
        type: string
      remove:
        description: 'whether to remove the path before fetching'
        required: false
        type: boolean
        default: true

    using: 'composite'
    

    steps:
      - name: remove path if required
        if: ${{ inputs.remove }} == 'true'
        run: |
          echo "Removing path: ${{ inputs.path }}"
          rm -rf ${{ inputs.path }}
        shell: bash
          
      - name: Set up Git
        run: |
          git restore --source ${{ inputs.branch }} --staged --worktree ${{ inputs.path }} ;
        shell: bash