name: 'Build Documentation'
description: 'Build MkDocs documentation and deploy to production branch'

inputs:
  production-branch:
    description: 'Production branch name'
    required: false
    default: 'production'
  docs-branch:
    description: 'Documentation source branch'
    required: false
    default: 'docs'
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'

outputs:
  version:
    description: 'Version string (v.yy.mm.dd)'
    value: ${{ steps.version.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ -f "src/mkdocs/requirements.txt" ]; then
          pip install -r src/mkdocs/requirements.txt
        else
          pip install mkdocs mkdocs-shadcn mkdocs-gen-files mkdocs-literate-nav pymdown-extensions
        fi

    - name: Fetch docs source
      shell: bash
      run: |
        echo "ðŸ“¥ Fetching docs source from ${{ inputs.docs-branch }} branch..."
        git fetch origin ${{ inputs.docs-branch }}:${{ inputs.docs-branch }}
        
        # CRITICAL: Delete old docs/ and src/ first to prevent mixing
        echo "ðŸ§¹ Removing old docs/ and src/..."
        rm -rf docs/ src/
        
        # Now copy fresh from docs branch
        git checkout origin/${{ inputs.docs-branch }} -- docs/ src/
        echo "âœ… Docs source ready"

    - name: Build documentation
      shell: bash
      working-directory: src/mkdocs
      run: |
        echo "ðŸ—ï¸ Building MkDocs site..."
        mkdocs build --clean
        echo "âœ… Build complete"

    - name: Deploy to docs/
      shell: bash
      run: |
        echo "ðŸ“¦ Deploying site to docs/..."
        rm -rf docs/
        cp -r src/mkdocs/site docs
        rm -rf src/
        echo "âœ… Deployed"

    - name: Set version
      id: version
      shell: bash
      run: |
        VERSION="v.$(date +'%y.%m.%d')"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "$VERSION" > docs/.version
        echo "ðŸ“Œ Version: $VERSION"

    - name: Upload docs artifact
      uses: actions/upload-artifact@v4
      with:
        name: docs-build
        path: docs/
        retention-days: 90

    - name: Commit to production
      shell: bash
      run: |
        git add docs/ index.html 2>/dev/null || git add docs/
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "ðŸ“š Build documentation ${{ steps.version.outputs.version }}"
          git push origin ${{ inputs.production-branch }}
          echo "âœ… Pushed to ${{ inputs.production-branch }}"
        fi
