name: 'Build and Deploy Versioned Documentation'
description: 'Build MkDocs documentation with mike versioning, deploy to docs branch'
author: 'CMIP-IPO'

inputs:
  production_branch:
    description: 'Branch containing source documentation'
    required: false
    default: 'production'
  docs_branch:
    description: 'Branch to deploy versioned docs to'
    required: false
    default: 'docs'
  mkdocs_dir:
    description: 'Directory containing mkdocs.yml (relative to repo root)'
    required: false
    default: 'src/mkdocs'
  python_version:
    description: 'Python version to use'
    required: false
    default: '3.11'
  version:
    description: 'Version to deploy (e.g., v1.0.0). If empty, reads from docs/.version'
    required: false
    default: ''
  set_latest:
    description: 'Set this version as latest alias'
    required: false
    default: 'true'
  github_token:
    description: 'GitHub token for pushing'
    required: true

outputs:
  version:
    description: 'Version that was deployed'
    value: ${{ steps.get_version.outputs.version }}
  deployed:
    description: 'Whether deployment occurred'
    value: ${{ steps.deploy.outputs.deployed }}

runs:
  using: 'composite'
  steps:
    # ==========================================
    # STEP 1: Setup and checkout production branch
    # ==========================================
    - name: Checkout production branch
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.production_branch }}
        fetch-depth: 0

    - name: Set up Git
      shell: bash
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        
        if [ -f "${{ inputs.mkdocs_dir }}/requirements.txt" ]; then
          pip install -r "${{ inputs.mkdocs_dir }}/requirements.txt"
        else
          pip install mkdocs mkdocs-material mike mkdocs-gen-files mkdocs-literate-nav pymdown-extensions
        fi
        
        # Ensure mike is installed
        pip install mike

    # ==========================================
    # STEP 2: Get version
    # ==========================================
    - name: Get version
      id: get_version
      shell: bash
      run: |
        if [ -n "${{ inputs.version }}" ]; then
          VERSION="${{ inputs.version }}"
        elif [ -f "docs/.version" ]; then
          VERSION=$(cat docs/.version | tr -d '[:space:]')
        else
          VERSION="v0.1.0"
          echo "$VERSION" > docs/.version
        fi
        
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "ðŸ“Œ Version: $VERSION"

    # ==========================================
    # STEP 3: Build with mike
    # ==========================================
    - name: Fetch docs branch for mike
      shell: bash
      run: |
        # Fetch the docs branch if it exists (mike needs it)
        if git ls-remote --heads origin ${{ inputs.docs_branch }} | grep -q ${{ inputs.docs_branch }}; then
          git fetch origin ${{ inputs.docs_branch }}:${{ inputs.docs_branch }} || true
        fi

    - name: Build and deploy with mike
      id: deploy
      shell: bash
      working-directory: ${{ inputs.mkdocs_dir }}
      run: |
        VERSION="${{ steps.get_version.outputs.version }}"
        
        echo "ðŸ—ï¸ Building documentation version $VERSION..."
        
        # Deploy with mike (builds and adds to versions)
        if [ "${{ inputs.set_latest }}" = "true" ]; then
          mike deploy "$VERSION" latest --update-aliases --branch ${{ inputs.docs_branch }}
        else
          mike deploy "$VERSION" --branch ${{ inputs.docs_branch }}
        fi
        
        # Set default to latest
        mike set-default latest --branch ${{ inputs.docs_branch }} || true
        
        echo "deployed=true" >> $GITHUB_OUTPUT
        echo "âœ… Mike deploy complete"

    # ==========================================
    # STEP 4: Save versions folder as artifact
    # ==========================================
    - name: Checkout docs branch to get versions
      shell: bash
      run: |
        # Create temp directory for versions
        mkdir -p /tmp/versions-artifact
        
        # Checkout docs branch content
        git checkout ${{ inputs.docs_branch }} -- . || true
        
        # Copy versions.json and version folders
        if [ -f "versions.json" ]; then
          cp versions.json /tmp/versions-artifact/
        fi
        
        # Copy all version directories
        for dir in */; do
          if [[ "$dir" =~ ^v[0-9] ]] || [ "$dir" = "latest/" ]; then
            cp -r "$dir" /tmp/versions-artifact/
          fi
        done
        
        # Go back to production branch
        git checkout ${{ inputs.production_branch }}

    - name: Upload versions artifact
      uses: actions/upload-artifact@v4
      with:
        name: docs-versions
        path: /tmp/versions-artifact
        retention-days: 1

    # ==========================================
    # STEP 5: Commit changes to production branch
    # ==========================================
    - name: Commit version file to production
      shell: bash
      run: |
        if [ -n "$(git status --porcelain docs/.version)" ]; then
          git add docs/.version
          git commit -m "ðŸ“š Update docs version to ${{ steps.get_version.outputs.version }}"
          git push origin ${{ inputs.production_branch }}
          echo "âœ… Version file committed to production"
        else
          echo "â„¹ï¸ No version file changes to commit"
        fi

    # ==========================================
    # STEP 6: Push docs branch
    # ==========================================
    - name: Push docs branch
      shell: bash
      run: |
        git push origin ${{ inputs.docs_branch }}
        echo "âœ… Docs branch pushed"

    # ==========================================
    # Summary
    # ==========================================
    - name: Summary
      shell: bash
      run: |
        echo "## ðŸ“š Documentation Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Setting | Value |" >> $GITHUB_STEP_SUMMARY
        echo "|---------|-------|" >> $GITHUB_STEP_SUMMARY
        echo "| Version | \`${{ steps.get_version.outputs.version }}\` |" >> $GITHUB_STEP_SUMMARY
        echo "| Production Branch | \`${{ inputs.production_branch }}\` |" >> $GITHUB_STEP_SUMMARY
        echo "| Docs Branch | \`${{ inputs.docs_branch }}\` |" >> $GITHUB_STEP_SUMMARY
        echo "| Set as Latest | \`${{ inputs.set_latest }}\` |" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "âœ… Documentation deployed successfully!" >> $GITHUB_STEP_SUMMARY

branding:
  icon: 'book-open'
  color: 'blue'
