name: Deploy static content to Pages

on:
  workflow_dispatch:
  # Uncomment to trigger on push to the production branch as well
  # push:
  #   branches: 
  #     - "production"


outputs:
  page_url:
    description: "The deployed GitHub Pages URL"
    value: ${{ steps.deployment.outputs.page_url }}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: production

      - name: Setup Pages
        uses: actions/configure-pages@v5


      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          retention-days: 0

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Display Deployed URL in GitHub Summary
        run: echo "### 🚀 Pages deployed at: [${{ steps.deployment.outputs.page_url }}](${{ steps.deployment.outputs.page_url }})" >> $GITHUB_STEP_SUMMARY