name: Deploy Static Content to GitHub Pages

on:
  workflow_dispatch:
  # Uncomment to trigger on push to the production branch as well
  # push:
  #   branches: 
  #     - "production"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    # Uncomment and configure this if using GitHub environments
    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    outputs:
      page_url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout production branch
        uses: actions/checkout@v4
        with:
          ref: production

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload site content
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          retention-days: 0

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Display deployed URL in summary
        run: echo "### 🚀 Pages deployed at [${{ steps.deployment.outputs.page_url }}](${{ steps.deployment.outputs.page_url }})" >> $GITHUB_STEP_SUMMARY
