site_name: CMIP-LD
site_url: https://cmip-ld.github.io/
repo_url: https://github.com/WCRP-CMIP/CMIPLD

docs_dir: docs
site_dir: site

theme:
  name: material
  custom_dir: copier/mkdocs/.src/mkdocs/overrides
  features:
    - navigation.footer
    - search.suggest
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - navigation.instant.progress
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
