name: Read Issue Content and Labels
description: Acton to process a new issue
# the main calling action must have the following permissions as well. 

permissions:
  issues: write
  pull-requests: write
  contents: write  # Allows creating branches, pushing changes to repositories

runs:
    using: 'composite'
    steps:

      - name: cmip-ld library
        id: install-cmipld
        uses: WCRP-CMIP/CMIPLD/actions/cmipld@main
      

      - name: Checkout src-data branch (for data files)
        uses: actions/checkout@v4
        with:
          ref: src-data
          fetch-depth: 0

      - name: Get handler scripts from main branch
        run: |
          git fetch origin main
          git checkout origin/main -- .github/ISSUE_SCRIPT
          echo "✓ Fetched handler scripts from main branch"
          ls -la .github/ISSUE_SCRIPT/
        shell: bash

      - name: Configure Git for simple push
        run: git config --global push.default simple
        shell: bash

      - name: Run Python script
        id: run_python
        env:
          # Only pass the issue number - script will fetch latest data via gh CLI
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GH_TOKEN: ${{ github.token }}
          GITHUB_TOKEN: ${{ github.token }}
          PYTHONIOENCODING: utf-8
          LC_ALL: C.UTF-8
          LANG: C.UTF-8

        run: |
          new_issue --issue ${{ github.event.issue.number }}

        shell: bash
        continue-on-error: false
