name: Find All Directories
description: Find all top-level subdirectories (excluding hidden directories)
outputs:
  directories:
    description: 'JSON array of all directory names'
    value: ${{ steps.find-dirs.outputs.directories }}
runs:
  using: composite
  steps:
    # - name: Checkout code
    #   uses: actions/checkout@v4
    #   with:
    #     fetch-depth: 1
    
    - name: Find all subdirectories
      id: find-dirs
      shell: bash
      run: |
        echo "Finding all directories..."
        directories=$(find . -mindepth 1 -maxdepth 1 -type d -not -path '*/.*' \
          | sed 's|^\./||' \
          | sort \
          | jq -R -s -c 'split("\n")[:-1]')
        
        # Handle case where no directories found
        if [ -z "$directories" ] || [ "$directories" = '[""]' ] || [ "$directories" = "null" ]; then
          directories='[]'
        fi
        
        echo "directories=$directories" >> "$GITHUB_OUTPUT"
        echo "Found directories: $directories"
