name: 'Check Context URLs'
description: 'Validate that all @context URLs in _context files are accessible'

runs:
  using: 'composite'
  steps:
    - name: Check context URLs
      shell: bash
      run: |
        set +e
        
        echo "## Context URL Validation" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Find all URLs in _context files
        URLS=$(grep -rh "http" --include="_context" --include="_context.json" . 2>/dev/null | \
               grep -oE 'https?://[^"]+' | sort -u)
        
        if [ -z "$URLS" ]; then
          echo "No external context URLs found." >> $GITHUB_STEP_SUMMARY
          exit 0
        fi
        
        PASSED=""
        FAILED=""
        
        for url in $URLS; do
          CODE=$(curl -s -o /dev/null -w "%{http_code}" -L -A "Mozilla/5.0" --max-time 10 "$url")
          if [ "$CODE" = "200" ]; then
            PASSED="${PASSED}| ${url} | ${CODE} |\n"
          else
            FAILED="${FAILED}| ${url} | ${CODE} |\n"
          fi
        done
        
        if [ -n "$PASSED" ]; then
          echo "### Accessible" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| URL | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
          printf "$PASSED" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
        fi
        
        if [ -n "$FAILED" ]; then
          echo "### Inaccessible" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| URL | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
          printf "$FAILED" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Warning:** Files depending on these contexts will not resolve correctly." >> $GITHUB_STEP_SUMMARY
        fi
        
        exit 0
