name: 'Check Context URLs'
description: 'Validate that all @context URLs in _context files are accessible'
inputs:
  create-issue:
    description: 'Create an issue if context URLs fail (default: false)'
    required: false
    default: 'false'
  github-token:
    description: 'GitHub token for creating issues (required if create-issue is true)'
    required: false

outputs:
  status:
    description: 'Overall status (success/failure)'
    value: ${{ steps.check.outputs.status }}
  failed-count:
    description: 'Number of failed context URLs'
    value: ${{ steps.check.outputs.failed_count }}

runs:
  using: 'composite'
  steps:
    - name: Check context URLs
      id: check
      shell: bash
      run: |
        echo "## Context URL Validation" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Find all context files
        CONTEXT_FILES=$(find . -name "_context" -o -name "_context.json" 2>/dev/null | grep -v node_modules | grep -v .git)
        
        if [ -z "$CONTEXT_FILES" ]; then
          echo "No _context files found." >> $GITHUB_STEP_SUMMARY
          echo "status=success" >> $GITHUB_OUTPUT
          echo "failed_count=0" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Extract unique URLs
        URLS=""
        for file in $CONTEXT_FILES; do
          FILE_URLS=$(cat "$file" | python3 -c "
        import json, sys
        try:
            data = json.load(sys.stdin)
            ctx = data.get('@context', [])
            if isinstance(ctx, str):
                if ctx.startswith('http'):
                    print(ctx)
            elif isinstance(ctx, list):
                for item in ctx:
                    if isinstance(item, str) and item.startswith('http'):
                        print(item)
        except:
            pass
        " 2>/dev/null)
          URLS="$URLS $FILE_URLS"
        done
        
        # Get unique URLs
        UNIQUE_URLS=$(echo $URLS | tr ' ' '\n' | sort -u | grep -v '^$')
        
        if [ -z "$UNIQUE_URLS" ]; then
          echo "No external context URLs found." >> $GITHUB_STEP_SUMMARY
          echo "status=success" >> $GITHUB_OUTPUT
          echo "failed_count=0" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Check each URL and collect results
        PASSED_URLS=""
        FAILED_URLS=""
        FAILED=0
        PASSED=0
        
        for url in $UNIQUE_URLS; do
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 "$url" 2>/dev/null || echo "000")
          
          if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "301" ] || [ "$HTTP_CODE" = "302" ]; then
            PASSED_URLS="$PASSED_URLS| \`$url\` | $HTTP_CODE |\n"
            PASSED=$((PASSED + 1))
          else
            FAILED_URLS="$FAILED_URLS| \`$url\` | $HTTP_CODE |\n"
            FAILED=$((FAILED + 1))
          fi
        done
        
        # Output results
        if [ $PASSED -gt 0 ]; then
          echo "### Accessible ($PASSED)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| URL | HTTP Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|-------------|" >> $GITHUB_STEP_SUMMARY
          printf "$PASSED_URLS" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
        fi
        
        if [ $FAILED -gt 0 ]; then
          echo "### Inaccessible ($FAILED)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| URL | HTTP Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|-------------|" >> $GITHUB_STEP_SUMMARY
          printf "$FAILED_URLS" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**$FAILED context URL(s) failed validation.** Files in this repository that depend on these contexts will not resolve correctly." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Possible causes:**" >> $GITHUB_STEP_SUMMARY
          echo "- The upstream context server is temporarily unavailable" >> $GITHUB_STEP_SUMMARY
          echo "- The URL is incorrect in the \`_context\` file" >> $GITHUB_STEP_SUMMARY
          echo "- The external context has been moved or removed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**To resolve:** Review the URLs listed above and verify they are correct and accessible." >> $GITHUB_STEP_SUMMARY
          
          echo "status=failure" >> $GITHUB_OUTPUT
          echo "failed_count=$FAILED" >> $GITHUB_OUTPUT
          printf '%s' "$FAILED_URLS" > /tmp/failed_urls.txt
        else
          echo "All context URLs are accessible." >> $GITHUB_STEP_SUMMARY
          echo "status=success" >> $GITHUB_OUTPUT
          echo "failed_count=0" >> $GITHUB_OUTPUT
        fi
        
        # Always exit 0 - do not fail the workflow
        exit 0

    - name: Create issue for failed contexts
      if: inputs.create-issue == 'true' && steps.check.outputs.status == 'failure'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        FAILED_COUNT: ${{ steps.check.outputs.failed_count }}
      run: |
        FAILED_URLS=$(cat /tmp/failed_urls.txt 2>/dev/null || echo "Unknown")
        
        # Check if issue already exists
        EXISTING=$(gh issue list --label "context-validation" --state open --json number --jq '.[0].number' 2>/dev/null || echo "")
        
        BODY="## Context URL Validation Failed

        **$FAILED_COUNT context URL(s) are not accessible:**

        $FAILED_URLS

        ### Impact
        Files in this repository that depend on these contexts will not resolve correctly until these URLs become available.

        ### Action Required
        - Check if the upstream context servers are available
        - Verify the URLs are correct in the \`_context\` files
        - Contact the maintainers of the external contexts if needed

        ---
        *This issue was automatically created by the context validation workflow.*"

        if [ -n "$EXISTING" ]; then
          gh issue comment "$EXISTING" --body "$BODY"
          echo "Updated existing issue #$EXISTING"
        else
          gh issue create \
            --title "Context URL Validation Failed" \
            --body "$BODY" \
            --label "context-validation,automated" || echo "Could not create issue"
          echo "Created new issue"
        fi
