name: 'Check Context URLs'
description: 'Validate that all @context URLs in _context files have resolvable domains'

runs:
  using: 'composite'
  steps:
    - name: Check context URLs
      shell: bash
      run: |
        set +e
        
        echo "## Context URL Validation" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Find URLs that are values of @context keys
        URLS=$(grep -rh '"@context"' --include="_context" --include="_context.json" . 2>/dev/null | \
               grep -oE '"@context"\s*:\s*"https?://[^"]+' | \
               grep -oE 'https?://[^"]+' | sort -u)
        
        if [ -z "$URLS" ]; then
          echo "No external context URLs found." >> $GITHUB_STEP_SUMMARY
          exit 0
        fi
        
        PASSED=""
        FAILED=""
        PASS_COUNT=0
        FAIL_COUNT=0
        
        for url in $URLS; do
          # Extract domain from URL
          DOMAIN=$(echo "$url" | sed -E 's|https?://([^/]+).*|\1|')
          
          # DNS lookup
          if host "$DOMAIN" > /dev/null 2>&1; then
            PASSED="${PASSED}| ${url} | ${DOMAIN} |\n"
            PASS_COUNT=$((PASS_COUNT + 1))
          else
            FAILED="${FAILED}| ${url} | ${DOMAIN} |\n"
            FAIL_COUNT=$((FAIL_COUNT + 1))
          fi
        done
        
        if [ -n "$PASSED" ]; then
          echo "### Resolvable (${PASS_COUNT})" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| URL | Domain |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
          printf "$PASSED" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
        fi
        
        if [ -n "$FAILED" ]; then
          echo "### Unresolvable (${FAIL_COUNT})" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| URL | Domain |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
          printf "$FAILED" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Warning:** These domains do not resolve. Context files will not work." >> $GITHUB_STEP_SUMMARY
        fi
        
        exit 0
