name: 'Build and Deploy MkDocs to Production Branch'
description: 'Build MkDocs on main branch, deploy to production branch using git worktree'
author: 'CMIP-IPO'

inputs:
  source_branch:
    description: 'Source branch to build from'
    required: false
    default: 'main'
  target_branch:
    description: 'Target branch to deploy to'
    required: false
    default: 'production'
  config_file:
    description: 'Path to mkdocs.yml config file'
    required: false
    default: '.src/mkdocs/mkdocs.yml'
  python_version:
    description: 'Python version to use'
    required: false
    default: '3.11'
  docs_dir:
    description: 'Directory name in target branch'
    required: false
    default: 'docs'

outputs:
  deployed_branch:
    description: 'Branch where docs were deployed'
    value: ${{ inputs.target_branch }}
  deployed_path:
    description: 'Path where docs were deployed'
    value: ${{ inputs.docs_dir }}

runs:
  using: 'composite'
  steps:
    - name: Set up Git configuration
      shell: bash
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git config --global init.defaultBranch main

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install MkDocs dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        
        # Install from requirements file if it exists
        if [ -f ".src/mkdocs/requirements.txt" ]; then
          echo "📦 Installing from .src/mkdocs/requirements.txt"
          pip install -r .src/mkdocs/requirements.txt
        else
          echo "📦 Installing default MkDocs packages"
          pip install mkdocs mkdocs-material mkdocs-plotly-plugin mkdocs-gen-files mkdocs-literate-nav pymdown-extensions
        fi

    - name: Verify MkDocs config
      shell: bash
      run: |
        if [ ! -f "${{ inputs.config_file }}" ]; then
          echo "❌ MkDocs config file not found: ${{ inputs.config_file }}"
          exit 1
        fi
        echo "✅ Found MkDocs config: ${{ inputs.config_file }}"

    - name: Build MkDocs
      shell: bash
      run: |
        echo "🏗️ Building MkDocs documentation..."
        mkdocs build -f "${{ inputs.config_file }}" -d "site"
        
        # Verify build was successful
        if [ ! -d "site" ]; then
          echo "❌ Build failed - no site directory created"
          exit 1
        fi
        
        if [ ! -f "site/index.html" ]; then
          echo "❌ Build failed - no index.html in output"
          exit 1
        fi
        
        echo "✅ MkDocs build completed"

    - name: Setup production branch with git worktree
      shell: bash
      run: |
        echo "🌿 Setting up production branch with git worktree..."
        
        # Check if production branch exists remotely
        if git ls-remote --heads origin ${{ inputs.target_branch }} | grep -q ${{ inputs.target_branch }}; then
          echo "📥 Production branch exists, fetching..."
          git fetch origin ${{ inputs.target_branch }}
          git worktree add production-deploy origin/${{ inputs.target_branch }}
        else
          echo "🆕 Creating new production branch..."
          git worktree add --orphan production-deploy ${{ inputs.target_branch }}
          cd production-deploy
          git rm -rf . 2>/dev/null || true
          cd ..
        fi
        
        echo "✅ Production branch worktree ready"

    - name: Deploy to production branch
      shell: bash
      run: |
        echo "📁 Deploying to production branch..."
        
        # Only clear the docs directory, keep everything else
        cd production-deploy
        
        # Remove only the docs directory if it exists
        if [ -d "${{ inputs.docs_dir }}" ]; then
          echo "🗑️ Clearing existing ${{ inputs.docs_dir }}/ directory..."
          rm -rf "${{ inputs.docs_dir }}"
        fi
        
        cd ..
        
        # Create fresh docs directory and copy built site
        mkdir -p production-deploy/${{ inputs.docs_dir }}
        cp -r site/* production-deploy/${{ inputs.docs_dir }}/
        
        # Add .nojekyll file for GitHub Pages (only if it doesn't exist)
        if [ ! -f "production-deploy/.nojekyll" ]; then
          touch production-deploy/.nojekyll
        fi
        
        # Add 404.html if it exists in build (only if it doesn't exist)
        if [ -f "site/404.html" ] && [ ! -f "production-deploy/404.html" ]; then
          cp site/404.html production-deploy/404.html
        fi
        
        echo "✅ Files transferred to production branch docs/ folder"

    - name: Commit and push to production
      shell: bash
      run: |
        echo "📤 Committing and pushing to production..."
        
        cd production-deploy
        
        # Add all files
        git add .
        
        # Check if there are changes to commit
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "📚 Deploy documentation from ${{ inputs.source_branch }} - $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin ${{ inputs.target_branch }}
          echo "✅ Documentation deployed to ${{ inputs.target_branch }} branch"
        else
          echo "ℹ️ No changes to deploy"
        fi
        
        cd ..

    - name: Cleanup worktree
      shell: bash
      run: |
        echo "🧹 Cleaning up worktree..."
        git worktree remove production-deploy --force || true
        echo "✅ Worktree cleaned up"

    - name: Deployment summary
      shell: bash
      run: |
        echo "## 🎉 MkDocs Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Source branch**: \`${{ inputs.source_branch }}\`" >> $GITHUB_STEP_SUMMARY
        echo "- **Target branch**: \`${{ inputs.target_branch }}\`" >> $GITHUB_STEP_SUMMARY
        echo "- **Config file**: \`${{ inputs.config_file }}\`" >> $GITHUB_STEP_SUMMARY
        echo "- **Docs directory**: \`${{ inputs.docs_dir }}\`" >> $GITHUB_STEP_SUMMARY
        echo "- **Status**: ✅ Deployment completed" >> $GITHUB_STEP_SUMMARY
        
        if [ -d "site" ]; then
          file_count=$(find "site" -type f | wc -l)
          size=$(du -sh "site" | cut -f1)
          echo "- **Files deployed**: \`$file_count\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Total size**: \`$size\`" >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 🌐 Next Steps" >> $GITHUB_STEP_SUMMARY
        echo "- Documentation is now available on the \`${{ inputs.target_branch }}\` branch" >> $GITHUB_STEP_SUMMARY
        echo "- GitHub Pages will automatically deploy from \`${{ inputs.target_branch }}/${{ inputs.docs_dir }}\`" >> $GITHUB_STEP_SUMMARY
