# file generated by setuptools-scm
# don't change, don't track in version control

__all__ = [
    "__version__",
    "__version_tuple__",
    "version",
    "version_tuple",
    "__commit_id__",
    "commit_id",
]

TYPE_CHECKING = False
if TYPE_CHECKING:
    from typing import Tuple
    from typing import Union

    VERSION_TUPLE = Tuple[Union[int, str], ...]
    COMMIT_ID = Union[str, None]
else:
    VERSION_TUPLE = object
    COMMIT_ID = object

version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE
commit_id: COMMIT_ID
__commit_id__: COMMIT_ID

<<<<<<< HEAD
__version__ = version = '0.0.7.dev288+g8d6d47179.d20251129'
__version_tuple__ = version_tuple = (0, 0, 7, 'dev288', 'g8d6d47179.d20251129')

__commit_id__ = commit_id = 'g8d6d47179'
=======
__version__ = version = '0.0.7.dev287+g108364574.d20251219'
__version_tuple__ = version_tuple = (0, 0, 7, 'dev287', 'g108364574.d20251219')

__commit_id__ = commit_id = 'g108364574'
>>>>>>> 97e37b4 (development)
