name: CI Validation Workflow

on:
  workflow_dispatch:

  workflow_call:


permissions:
  actions: write
  contents: write

jobs:

  find-all-directories:
    if: ${{ inputs.updated == false }}
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.find-dirs.outputs.directories }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: src-data
          
      - name: Find all subdirectories (excluding . and hidden dirs)
        id: find-dirs
        run: |
          echo "Finding all directories..."
          directories=$(find . -mindepth 1 -maxdepth 1 -type d -not -path '*/.*' \
            | sed 's|^\./||' \
            | sort \
            | jq -R -s -c 'split("\n")[:-1]')
          
          # Handle case where no directories found
          if [ -z "$directories" ] || [ "$directories" = '[""]' ] || [ "$directories" = "null" ]; then
            directories='[]'
          fi
          
          echo "directories=$directories" >> "$GITHUB_OUTPUT"

      # Context
      - name: Correct Contexts
        run: |
          update_ctx

      # README
      - name: README files
        run: |
          echo "Updating README files..."
          echo "Add something here"



      ## Auto-commit changes
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Updating Readme and Context files"
          branch: src-data
          file_pattern: "*/_context"
          commit_user_name: "cmip-ipo automation"
          commit_user_email: "actions@wcrp-cmip.org"
          push_options: "--force"
        continue-on-error: true






  process-directories:
    needs: find-all-directories
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJson(needs.find-all-directories.outputs.directories || '["."]') }}
      fail-fast: false
      max-parallel: 10

    steps:
      
      - name: Get a list of directories with updated files
        id: install-cmipld
        uses: WCRP-CMIP/CMIPLD/actions/cmipld@main

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: src-data
          

      # Validate
      - name: Validate JSON-LD from files
        run: |
          validate_json ${{matrix.directory}} --add-coauthors --verbose
          

          
      - name: Validate JSON-LD from URL
        run: |
          if [ -f "${{ matrix.directory }}/graph.jsonld" ]; then
            # Fixed the pyld command syntax
            pyld test "${{ matrix.directory }}/graph.jsonld" > /dev/null 2>&1 || {
              echo "⚠️ Validation failed"
              exit 1
            }
          else
            echo "⚠️ No graph.jsonld found in ${{ matrix.directory }}"
            exit 1
          fi

      ## Auto-commit changes
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update JSON-LD graph in ${{ matrix.directory }}"
          branch: production
          file_pattern: "${{ matrix.directory }}/*graph*"
          commit_user_name: "cmip-ipo automation"
          commit_user_email: "actions@wcrp-cmip.org"
          push_options: "--force"
        continue-on-error: true